# Generated by Django 4.2.2 on 2023-06-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_question_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="create_data",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="create_data",
            new_name="create_date",
        ),
    ]
